name: Wisata Bandung
favicon: null
layout_spectrum: 0
typography_spectrum: 0.17098
title: Seratour no 1 tour travel provider in Bandung
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#4e3b41'
    - '#988c9a'
    - '#cf6917'
  brandStrength: 0.6875
  lightness: 1
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
